add react-router-dom
htmlacademy-react/425039-six-cities-7 pull request #4
Opened 2021-06-10 20:40 UTC by elenagradovich

2021-06-13 15:05 UTC, copperkraft requested changes

2021-06-13 15:05 UTC, copperkraft commented on project/src/components/header/header.jsx
> +  const isLogged = authInfo && true;
Не совсем понял, для чего нужна часть с `&& true`. Если ты хочешь, чтобы твой емейл не попал в разметку через `&&`, ты можешь написать `!!email && (.....)` (двойное отрицание)

2021-06-13 15:05 UTC, copperkraft commented on project/src/components/room/room.jsx
> +  const {rating, images, isPremium, isFavorite, price, goods, host, description, maxAdults, bedrooms, type} = data;
Когда используешь больше 3 однотипных элементов, лучше все же переносить каждый на новую строку.

2021-06-14 08:04 UTC, elenagradovich commented on project/src/components/room/room.jsx
> +  const {rating, images, isPremium, isFavorite, price, goods, host, description, maxAdults, bedrooms, type} = data;
ок

2021-06-14 08:06 UTC, elenagradovich commented on project/src/components/app/app.jsx
> +          <Favorites data={favoriteHotels} authInfo={authInfo} />
ок

2021-06-14 08:06 UTC, elenagradovich commented on project/src/utils/common.js
> +  data && data.forEach((hotel) => {
ок

2021-06-14 08:13 UTC, elenagradovich commented on project/src/components/header/header.jsx
> +  const isLogged = authInfo && true;
ок

2021-06-14 08:16 UTC, elenagradovich commented on project/src/utils/common.js
> +    const hotelName = hotel.city.name;
ок

2021-06-14 08:16 UTC, elenagradovich commented on project/src/utils/common.js
> +  let hotelsByPlace = [];
ок

2021-06-14 08:47 UTC, elenagradovich commented on project/src/utils/common.js
> +      hotels.set(hotelName.toUpperCase(), hotelsByPlace);
круто )

2021-06-15 08:39 UTC, copperkraft commented on project/src/components/favorites/favorites.jsx
> +function Favorites (props) {
Вместо props можно сразу писать `({ hotels, authInfo }) `

2021-06-15 08:44 UTC, copperkraft commented on project/src/components/room/room.jsx
> +    type} = hotels[0];
```
  bedrooms,
  type
} = hotels[0];
``` 
это раз. Во вторых, можно `const foo = bar[0]` заменить на `const [foo] = bar`

2021-06-15 08:45 UTC, merged